name: mimapasosfront
description: "Sistema de Evacuación Ante Tsunami - Valparaíso"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_map: ^6.1.0
  latlong2: 0.9.0  # Mantenemos la 0.9.0 fija para evitar el error de Windows
  font_awesome_flutter: ^10.7.0 # Para el botón de Google
  geolocator: ^14.0.2
  audioplayers: ^6.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/